server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    # Optimizations for serving large files (like your 87MB .exe)
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    # Handle React routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}
